]
landingi/ui-kit pull request #128
Opened 2022-01-17 11:28 UTC by fifijo

https://landingi.atlassian.net/jira/software/projects/SPA/boards/105?selectedIssue=SPA-311

2022-01-17 13:33 UTC, bartlomiej-kochanowicz approved these changes

2022-01-17 22:25 UTC, fifijo commented
@bartlomiej-kochanowicz Tutaj też mam błąd z JSX, to samo co tutaj https://github.com/landingi/ui-kit/pull/134#issuecomment-1014911634

2022-01-18 11:32 UTC, bartlomiej-kochanowicz requested changes

2022-01-18 11:32 UTC, bartlomiej-kochanowicz commented on src/shared/components/global/TimingToast/TimingToast.js
> +      [styles[`toast--hidden`]]: !!isActive
a może Boolean()

2022-01-18 12:14 UTC, nataliapietrzak-landingi commented on src/shared/components/global/TimingToast/TimingToast.js
> +      [styles[`toast--hidden`]]: !!isActive
ja zaś wolę !! :trollface:

2022-01-18 12:14 UTC, nataliapietrzak-landingi approved these changes

2022-01-18 17:12 UTC, merged