[EDI-903]Dropdown css module
landingi/ui-kit pull request #145
Opened 2022-01-20 12:52 UTC by fifijo

https://landingi.atlassian.net/jira/software/projects/EDI/boards/90/backlog?selectedIssue=EDI-903&text=Dropd

2022-01-21 10:35 UTC, bartlomiej-kochanowicz approved these changes

2022-01-21 10:58 UTC, OskarJankowiak-Landingi requested changes

2022-01-21 10:58 UTC, OskarJankowiak-Landingi commented on src/shared/components/ui/Dropdown/Dropdown.js
> +        className
className idzie jako string lub tablica, przekazane w obiekcie się wysypie.

2022-01-21 10:58 UTC, OskarJankowiak-Landingi commented on src/shared/components/ui/Dropdown/Dropdown.js
> +        className
j.w, dodatkowo to jest jeden props className a jest rozbity na style dla dwóch rzeczy, przekazując sobie jakiś className klasy zostaną dodane w dwóch miejscach takie same.

2022-01-24 13:12 UTC, bartlomiej-kochanowicz submitted a review, later dismissed

2022-01-24 13:17 UTC, OskarJankowiak-Landingi submitted a review, later dismissed

2022-01-24 13:47 UTC, merged