[SPA-119]Search input styles, badge color and infinite scroll refactor
landingi/ui-kit pull request #161
Opened 2022-01-27 12:54 UTC by bartlomiej-kochanowicz

Preview:
![Screenshot 2022-01-27 at 12 15 56](https://user-images.githubusercontent.com/89905016/151362900-caeadc95-a748-43aa-8cff-a6d80d4c2af0.png)
![Screenshot 2022-01-27 at 12 15 35](https://user-images.githubusercontent.com/89905016/151362907-0879c659-409f-4849-9aa7-062fe131f66c.png)

2022-01-27 12:57 UTC, fifijo approved these changes

2022-01-27 12:58 UTC, bartlomiej-kochanowicz commented
CI zaraz naprawie

2022-01-28 15:04 UTC, fifijo commented
@bartlomiej-kochanowicz konflikty

2022-01-31 11:21 UTC, fifijo approved these changes

2022-01-31 11:21 UTC, fifijo commented
@bartlomiej-kochanowicz konflikty :)

2022-01-31 17:59 UTC, fifijo requested changes
Sprawdziłeś dokładnie Search bo nie widzę, że usunąłeś jeden przykład z MDX

2022-01-31 17:59 UTC, fifijo commented on src/shared/components/ui/Dot/Dot.js
> +const Dot = ({ variant, label, className }) => {
Brakuje jsdoc

2022-01-31 18:00 UTC, fifijo requested changes
.

2022-02-01 07:27 UTC, fifijo approved these changes

2022-02-01 07:28 UTC, merged