[GRO-2514]Test @components/ui/Select
landingi/ui-kit pull request #163
Opened 2022-01-28 07:52 UTC by lukaszochwat-landingi

Test @components/ui/Select
https://landingi.atlassian.net/browse/GRO-2514?atlOrigin=eyJpIjoiMWE1MjRlOTdiMjgyNDI1YzhlYTNjMmE5ZTJjY2M4MWEiLCJwIjoiaiJ9

2022-01-28 11:28 UTC, fifijo requested changes
Dodaj też css-module

2022-01-31 07:31 UTC, nataliapietrzak-landingi approved these changes

2022-02-01 07:27 UTC, bartlomiej-kochanowicz requested changes

2022-02-01 07:27 UTC, bartlomiej-kochanowicz commented on src/shared/components/ui/Select/Select.js
>   * The default properties.
nie dodajemy komentarzy w tym miejscu już, tylko jsdoc

2022-02-03 10:11 UTC, fifijo submitted a review, later dismissed

2022-02-03 10:12 UTC, fifijo commented
@lukaszochwat-landingi konflikty

2022-02-03 10:29 UTC, fifijo requested changes

2022-02-03 10:29 UTC, fifijo commented on src/shared/components/ui/Select/Select.js
>  //TODO Select css, test
Usuń todo bo test i css już gotowe

2022-02-03 10:33 UTC, bartlomiej-kochanowicz approved these changes

2022-02-03 10:40 UTC, fifijo approved these changes

2022-02-03 11:09 UTC, merged