[PI-1295]Button updated
landingi/ui-kit pull request #217
Opened 2022-04-05 10:47 UTC by jaroslawkucharski-landingi

https://landingi.atlassian.net/browse/PI-1295

Button updated

2022-04-05 13:01 UTC, fifijo requested changes
Ogólnie działa ale wprowadź poprawkę z klasami i trzeba jeszcze raz sprawdzić

2022-04-05 13:01 UTC, fifijo commented on src/shared/components/ui/Button/Button.js
> +      [styles['button--publish']]: variant === 'publish',
to można zmniejszyć do jednej linii
`[styles[`button--${variant}`]]: variant`

to samo dotyczy
`[styles['button--right']]: align === 'right',` => `[styles[`button--${align}`]]: align`

2022-04-06 06:43 UTC, fifijo approved these changes

2022-04-06 07:52 UTC, nataliapietrzak-landingi approved these changes

2022-04-06 07:54 UTC, bartlomiej-kochanowicz approved these changes

2022-04-06 07:57 UTC, merged