[APP-749]Textarea updated
landingi/ui-kit pull request #350
Opened 2022-10-11 13:05 UTC by jaroslawkucharski-landingi

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1oLCIoyUtVAf5oTT65eFWC4ALdXL6lPo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=IfmtPsq)
https://landingi.atlassian.net/browse/APP-749

Textarea updated.

2022-10-11 13:39 UTC, OskarJankowiak-Landingi requested changes

2022-10-11 13:39 UTC, OskarJankowiak-Landingi commented on src/components/Textarea/Textarea.js
> +  const isTouched = touched[name]
Kuknij do /form/input na helper getDeepValue dodałbym to tutaj dla spójności
Pomaga to gdy formik ma zagnieżdżony stan `np const errrors = {object: {textarea: true}}` aby wydobywać errora z zagnieżdżonego obiektu

2022-10-11 13:41 UTC, OskarJankowiak-Landingi commented on src/components/Textarea/Textarea.js
> +  const isTouched = touched[name]
rozwiązanie jak najbardziej poprawne, ale nie zadziała jak formularz będzie bardziehj rozbudowany :P

2022-10-11 13:50 UTC, OskarJankowiak-Landingi requested changes

2022-10-11 13:50 UTC, OskarJankowiak-Landingi commented on src/components/Textarea/Textarea.module.scss
> +  &__label--error {
tutaj np jest w porządku label to element podrzędny, a error to variant, można to zrobić jeszcze tak aby w przypadku kolejnych variantów do labela rozbudowywać je według struktury poniżej :P 
```

&__label {
   &--error {
     tutaj style
   }
}
```

2022-10-12 05:41 UTC, jaroslawkucharski-landingi commented on src/components/Textarea/Textarea.module.scss
> -  &--tiny {
@OskarJankowiak-Landingi masz rację. Mi się coś wczoraj powaliło.

2022-10-12 06:13 UTC, OskarJankowiak-Landingi approved these changes

2022-10-12 06:18 UTC, merged