Css-Modules and mdx code formatting
landingi/ui-kit pull request #80
Opened 2021-12-21 17:26 UTC by bartlomiej-kochanowicz

Main changes:

- add support for css-modules, now we don't use styles() func to styled components, just import styles with .module.scss - extension and use it
- for conditional styling I added hook called "useStyles"
- now for documentation files create files with .mdx extension insted .md. It allows better code formatting :)
- Components: "Tooltip", "Input" already have new styling method
- prettier config is now in separate file .prettierrc

2021-12-21 18:26 UTC, bartlomiej-kochanowicz commented
Wszystko już działa, dopisałem jeszcze testy do nowego hooks useStyles. Zostało jeszcze poprawienie testów w tooltip.js bo widzę, że spadły

2021-12-21 20:06 UTC, fifijo requested changes

2021-12-21 20:06 UTC, fifijo commented on src/shared/components/ui/Input/Input.js
> +  console.log(styles)
do usunięcia console.log. Można dodać do rules w eslicie aby sprawdzało console.log

2021-12-23 12:49 UTC, fifijo approved these changes

2021-12-28 07:25 UTC, OskarJankowiak-Landingi submitted a review, later dismissed

2021-12-28 15:39 UTC, fifijo approved these changes

2022-01-03 11:13 UTC, fifijo approved these changes

2022-01-03 11:23 UTC, OskarJankowiak-Landingi approved these changes

2022-01-03 11:26 UTC, merged