[EDI-881]Accordion2 css-modules
landingi/ui-kit pull request #87
Opened 2022-01-04 11:30 UTC by bartlomiej-kochanowicz

Jira: https://landingi.atlassian.net/browse/EDI-881

2022-01-04 12:04 UTC, fifijo requested changes

2022-01-04 12:04 UTC, fifijo commented on src/shared/components/ui/Accordion2/Item/AccordionItem.js
> +import styles from './../Accordion.module.scss'
Użyj pełną ścieżkę @components/blabla/Accordion.moudule.scss

2022-01-04 19:57 UTC, fifijo submitted a review, later dismissed

2022-01-05 08:12 UTC, nataliapietrzak-landingi approved these changes

2022-01-05 08:28 UTC, fifijo approved these changes

2022-01-05 08:29 UTC, merged